name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - uses: actions/setup-dotnet@v1 # Adds a step to checkout the repository code
      with:
        dotnet-version: '6.0.x'
    - run: dotnet build


    - name: test dotnet 
      with:
        dotnet-version: '6.0.x'
      run: dotnet test

    - name: typescript tests 
      with:
        dotnet-version: '6.0.x'
      working-directory: DotnetTemplate.Web
      run: npm t

    - name: typescript linter 
      with:
        dotnet-version: '6.0.x'
      working-directory: DotnetTemplate.Web
      run: npm run lint

